@startuml
'https://plantuml.com/class-diagram




class ConsultUsersInTheWaitingRoomUI

class ConsultUsersInTheWaitingRoomController{
+setVaccinationCenter()
+getArrivalsList()
+listOfUsersInTheWaitingRoom(VaccinationCenter vaccinationCenter)
}


class VaccinationCenter{
+getArrivalsList()
}

class Company{
+getSnsUsersList()
}

class SnsUser


left to right direction

ConsultUsersInTheWaitingRoomUI .> ConsultUsersInTheWaitingRoomController
ConsultUsersInTheWaitingRoomController .r.> Company
Company -> SnsUser
ConsultUsersInTheWaitingRoomController ..> VaccinationCenter


@enduml